#!/bin/sh

# stash any unstaged changes
git stash -q --keep-index

# run the tests
./run_tests.sh

# store the last exit code in a variable
RESULT=$?

# unstash the unstashed changes
git stash pop -q

# return the tests exit code
exit $RESULT
